# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Samuel Workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pytest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
  
  docker:
    runs-on: ubuntu-latest
    needs: pytest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_SAMUEL_USERNAME }}
          password: ${{ secrets.DOCKER_SAMUEL_PASSWORD }}

      - name: Build Docker image
        run: docker build -t devops .

      - name: Tag Docker image with latest
        run: docker tag devops ${{ secrets.DOCKER_SAMUEL_USERNAME }}/devops:latest

      - name: Tag Docker image with '1.1'
        run: docker tag devops ${{ secrets.DOCKER_SAMUEL_USERNAME }}/devops:1.2


      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_SAMUEL_USERNAME }}/devops:latest

